### ISSUE TITLE
Help setup spaces to have Tax ID and D.U.N.S. number ready to receive funding

### ISSUE THREAD

**Issue by seanauriti** [nationofmakers/funding-gateway#4]

**Comment by danawoodman** [comment]
Tax ID is easy but I'm sure people don't know how to do it. Would be a great resource page on the site?

**Comment by seanauriti** [comment]
I was thinking we can have another field in the attendee list for Tax ID / DUNS... yes and would also be a good resource page.

**Comment by danawoodman** [comment]
Make sense 👍 

I'm thinking I want to jump into some sorta placeholder website sometime next week. I feel like it will help us be a bit more structured overall, even if it's only internal. Thanks for getting it started @seanauriti~

**Comment by seanauriti** [comment]
https://github.com/Spurri/website/issues active development is happening here, please add any issues or suggestions to that repo.
